services:
  database:
    image: "cockroachdb/cockroach:latest-v24.3"
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "./data/crdb:/cockroach/cockroach-data"
  s3:
    image: "minio/minio"
    ports: 
      - "9011:9000"
      - "9012:9001"
    command: server /data --console-address :9001
    volumes:
      - "./data/s3:/data"
  