chorister:
  base-url: "http://localhost:8080/"
  datasource:
    system:
      url: "jdbc:postgresql://127.0.0.1:26257/chorister?sslmode=disable"
      driver-class-name: org.postgresql.Driver
      username: root
      password:
      hikari:
        connection-test-query: SELECT 1
        maximum-pool-size: 50
        minimum-idle: 20
    user:
      url: ${chorister.datasource.system.url}
      username: app_user
      password: user1234!
server:
  port: 8090
spring:
  liquibase:
    parameters:
      username: app_user
      password: user1234!
      database: chorister
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth/v2/keys
        opaquetoken:
          introspection-uri: http://localhost:9000/oauth/v2/introspect
          client-id: ${CHORISTER_API_CLIENT_ID}
          client-secret: ${CHORISTER_API_SECRET}
debug: true
logging:
  level:
    org:
      springframework:
        security: TRACE
        web: DEBUG
      zalando:
        logbook: TRACE
    reactor:
      netty:
        http:
          client: DEBUG
zitadel:
  base-url: http://localhost:9000/management/v1
  admin-access-token: ${CHORISTER_ADMIN_ACCESS_TOKEN}
s3:
  endpoint-url: http://localhost:9011
  bucket-name: "chorister-files"
  region: eu1
  access-key: minioadmin
  secret-key: minioadmin